version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hrms_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hrms_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: hrms_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - hrms_network
    depends_on:
      - postgres

networks:
  hrms_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
